FROM ubuntu:20.04


#setting up user
RUN useradd -ms /bin/bash sandbox

#setup work directory
WORKDIR /home/sandbox

#update ubuntu machine
RUN apt update && apt upgrade -y

#install nano and curl
RUN apt install curl nano -y

#install node.js
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && apt-get install -y nodejs

#config terminal to display current workdir
RUN echo "PS1= '\w ' " >> /home/sandbox/.bashrc

#setting final workdir
WORKDIR /home/sandbox/app

